name: Quality and Security Check
    
    on:
      push:
        branches: [ main ]
      pull_request:
        branches: [ main ]
    
    jobs:
      quality_and_security:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Cache npm dependencies
            uses: actions/cache@v3
            with:
              path: ~/.npm
              key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                ${{ runner.os }}-npm-
    
          - name: TruffleHog OSS Scan
            uses: trufflesecurity/trufflehog@main
            with:
              path: ./
              base: ${{ github.event.before }}
              head: ${{ github.sha }}
              extra_args: --debug --only-verified
    
          - name: Super-Linter
            uses: github/super-linter@v5
            env:
              DEFAULT_BRANCH: main
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
